before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

builds:
  - id: build
    main: ./
    binary: catpaw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{ .Tag }}-{{.Commit}}

archives:
  - id: archive
    rlcp: true
    builds:
      - build
    format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf.d/**
      - LICENSE
      - README.md


release:
  github:
    owner: cprobe
    name: catpaw
  name_template: "v{{ .Version }}"
