version: 2
name: go1.20编译二进制文件
description: 显示二进制文件信息，可使用scp节点复制到其他服务器
global:
  concurrent: 1
trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: create_tag
      ruleset:
        - param-ref: tag
          operator: REG_EXP
          value: '"v.*"'
      ruleset-operator: AND
workflow:
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.9
    input:
      remote_url: '"https://gitlink.org.cn/UlricQin/catpaw.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 1
    needs:
      - start
  - ref: start
    name: 开始
    task: start
  - ref: end
    name: 结束
    task: end
    needs:
      - shell_0
  - ref: golang_build_node_0
    name: golang_build_node
    task: yystopf/golang_build_node@0.0.2
    input:
      workspace: git_clone_0.git_path
      out_bin_name: '"build-test-bin"'
      goos: '"linux"'
      goarch: '"amd64"'
    needs:
      - git_clone_0
  - ref: shell_0
    name: 显示go build bin文件
    image: docker.jianmuhub.com/library/alpine:3.17.0
    env:
      GO_BIN_FILE: golang_build_node_0.bin_dir
    script:
      - ls  -lsh  ${GO_BIN_FILE}
    needs:
      - golang_build_node_0

