version: 2
name: workflow01
description: ""
global:
  concurrent: 1
trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: create_tag
      ruleset:
        - param-ref: tag
          operator: REG_EXP
          value: '"v.*"'
      ruleset-operator: AND
workflow:
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.9
    input:
      remote_url: '"https://gitlink.org.cn/UlricQin/catpaw.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 1
    needs:
      - start
  - ref: start
    name: 开始
    task: start
  - ref: end
    name: 结束
    task: end
    needs:
      - go_build_node_0
  - ref: go_build_node_0
    name: go_build_node
    task: echo/go_build_node@0.0.3
    input:
      workspace: git_clone_0.git_path
      out_bin_name: '"test"'
      goos: '"linux"'
      goarch: '"amd64"'
    needs:
      - git_clone_0

