[global]
interval = "15s"

[global.labels]
from_agent = "catpaw"
from_hostname = "$hostname"
from_hostip= "$ip"

# [log]
# level = "info"
# format = "json"
# output = "stdout"
# fields = {}

[flashduty]
url = "https://api.flashcat.cloud/event/push/alert/standard?integration_key=xx"
timeout = "10s"
